---
name: "Trakt"
guid: "4fe3201e-d6ae-4f2e-8917-e12bda571281"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-trakt.png"
version: 22
targetAbi: "10.8.8.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Record your watched media with Trakt"
description: >
  Record your watched media with Trakt.

category: "General"
artifacts:
  - "Trakt.dll"
changelog: |-
  - Update README.md (#188) @methbkts

  ### New features and improvements ###
  - Fix episode matching for sync from trakt task (#191) @h3llrais3r

  ### Bug Fixes ###
  - Fix episode matching for sync from trakt task (#191) @h3llrais3r
