---
name: "Trakt"
guid: "4fe3201e-d6ae-4f2e-8917-e12bda571281"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-trakt.png"
version: 26
targetAbi: "10.10.0.0"
framework: "net8.0"
owner: "jellyfin"
overview: "Record your watched media with Trakt"
description: >
  Record your watched media with Trakt.

category: "General"
artifacts:
  - "Trakt.dll"
changelog: |-
  - 10.10 support (#238) @crobibero

  ### Dependency updates ###
  - Update dependency Microsoft.Extensions.Http to v8 (#187) @renovate
