---
name: "Trakt"
guid: "4fe3201e-d6ae-4f2e-8917-e12bda571281"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-trakt.png"
version: 23
targetAbi: "10.8.9.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Record your watched media with Trakt"
description: >
  Record your watched media with Trakt.

category: "General"
artifacts:
  - "Trakt.dll"
changelog: |2-
  ### New features and improvements ###
  - Added config parameter Don't remove items from trakt (#196) @addamanth

  ### Bug Fixes ###
  - Sync  if not set locally (#201) @blackwind
  - Fix episode last played date syncing (#199) @Shadowghost
