---
name: "Trakt"
guid: "4fe3201e-d6ae-4f2e-8917-e12bda571281"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-trakt.png"
version: 21
targetAbi: "10.8.5.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Record your watched media with Trakt"
description: >
  Record your watched media with Trakt.

category: "General"
artifacts:
  - "Trakt.dll"
changelog: |2-
  ### New features and improvements ###
  - Do not hammer the API (#175) @Shadowghost

  ### Bug Fixes ###
  - Do not hammer the API (#175) @Shadowghost
  - Prevent setting local item as unwatched on sync (#169) @Shadowghost

  ### Code or Repo Maintenance ###
  - Add more info to debug logs (#171) @sambartik
