---
name: "Trakt"
guid: "4fe3201e-d6ae-4f2e-8917-e12bda571281"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-trakt.png"
version: 27
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Record your watched media with Trakt"
description: >
  Record your watched media with Trakt.

category: "General"
artifacts:
  - "Trakt.dll"
changelog: |-
  - Jellyfin 10.11 support (#250) @crobibero
  - Migrate analyzers and fix NPE (#245) @Shadowghost
  - Fix typo in trakt.html (#241) @maroessler
