---
name: "Trakt"
guid: "4fe3201e-d6ae-4f2e-8917-e12bda571281"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-trakt.png"
version: 25
targetAbi: "10.9.0.0"
framework: "net8.0"
owner: "jellyfin"
overview: "Record your watched media with Trakt"
description: >
  Record your watched media with Trakt.

category: "General"
artifacts:
  - "Trakt.dll"
changelog: |-
  - 10.9 (#233) @crobibero

  ### Dependency updates ###
  - Update dependency StyleCop.Analyzers to v1.2.0-beta.556 (#214) @renovate
