---
name: "jellyfin-plugin-trakt"
guid: "4fe3201e-d6ae-4f2e-8917-e12bda571281"
version: "2" # Please increment with each pull request
jellyfin_version: "10.3.0" # The earliest binary-compatable version
nicename: "Trakt"
owner: "jellyfin"
description: "Record your watched media with Trakt"
overview: >
  Record your watched media with Trakt.
category: "General"
build_type: "build.py"
dotnet_configuration: "Release"
dotnet_framework: "netstandard2.0"
csproj: "Trakt/Trakt.csproj"
artifacts:
  - "Trakt.dll"
