name: '📝 Create/Update Release Draft & Release Bump PR'

on:
  push:
    branches:
      - master
    paths-ignore:
      - build.yaml
  workflow_dispatch:
  repository_dispatch:
    types:
      - update-prep-command

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/changelog.yaml@672e46d3ec5096731edbb7581ca872f3d8175cf8 # master
    with:
      repository-name: jellyfin/jellyfin-plugin-trakt
    secrets:
      token: ${{ secrets.JF_BOT_TOKEN }}
