# Allows for the definition of PR and Issue /commands
name: '📟 Slash Command Dispatcher'

on:
  issue_comment:
    types:
      - created

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/command-dispatch.yaml@bd147a5ba80bc60d6c94f8842afe716f6a2f626a # master
    secrets:
      token: ${{ secrets.JF_BOT_TOKEN }}
