# Allows for the definition of PR and Issue /commands
name: '📟 Slash Command Dispatcher'

on:
  issue_comment:
    types:
      - created

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/command-dispatch.yaml@b40eae0e963055a9981e8b076beee8ae1b1207ad # master
    secrets:
      token: ${{ secrets.JF_BOT_TOKEN }}
