name: '🚀 Publish Plugin'

on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/publish.yaml@b40eae0e963055a9981e8b076beee8ae1b1207ad # master
    with:
      version: ${{ github.event.release.tag_name }}
      is-unstable: ${{ github.event.release.prerelease }}
    secrets:
      deploy-host: ${{ secrets.REPO_HOST }}
      deploy-user: ${{ secrets.REPO_USER }}
      deploy-key: ${{ secrets.REPO_KEY }}
