name: '🏷️ Sync labels'

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/sync-labels.yaml@672e46d3ec5096731edbb7581ca872f3d8175cf8 # master
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
