name: '🏷️ Sync labels'

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/sync-labels.yaml@c5847d4d5a8a577632723fe0ff120d9ddcbc5d09 # master
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
