name: '🧪 Test Plugin'

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/test.yaml@b40eae0e963055a9981e8b076beee8ae1b1207ad # master
