name: '🧪 Test Plugin'

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/test.yaml@5ebf9f9455736773ab6f94cdb19fb903ece41b83 # master
